DATASET_PATH = ${CURDIR}/toy_data

clean-pyc:
	find . -name '*.pyc' -exec rm --force {} +
	find . -name '*.pyo' -exec rm --force {} +
	name '*~' -exec rm --force  {} 

clean-build:
	rm --force --recursive build/
	rm --force --recursive dist/
	rm --force --recursive *.egg-info

run:
	python2.7 mini.py --dataset_folder_path=$(DATASET_PATH)
